version: '3.8'

services:
  # --- Banco de Dados PostgreSQL ---
  postgres:
    image: astraonline/postgrespgvector:2024
    environment:
      - POSTGRES_USER=raunaimer
      - POSTGRES_PASSWORD=qbO#259Qq # A senha original
      - POSTGRES_DB=raunaimer
      - TZ=America/Sao_Paulo
      - PG_MAX_CONNECTIONS=100
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - network_public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  # --- Cache em Memória com Redis ---
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    networks:
      - network_public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  # --- Aplicação Backend (API) ---
  backend:
    image: raunaimer-backend:latest
    networks:
      - network_public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=false"

  # --- Aplicação Frontend (Interface do Usuário) ---
  frontend:
    image: raunaimer-frontend:latest
    networks:
      - network_public
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.raunaimer.rule=Host(`app.raunaimer.adv.br`)"
        - "traefik.http.routers.raunaimer.entrypoints=websecure"
        - "traefik.http.routers.raunaimer.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.raunaimer.loadbalancer.server.port=80"

volumes:
  postgres_data:
    external: true
  redis_data:
    external: true

networks:
  network_public:
    external: true
  