name: Test Build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚀 Checkout code
      uses: actions/checkout@v4
      
    - name: 📦 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: 📦 Install dependencies (Frontend)
      run: npm install
      
    - name: 📦 Install dependencies (Backend)
      run: |
        cd backend
        npm install
        cd ..
        
    - name: 🔨 Build Frontend
      run: npm run build
      
    - name: 🔨 Build Backend
      run: |
        cd backend
        npm run build
        cd ..
        
    - name: ✅ Build completed
      run: echo "Build testado com sucesso!" 